<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function citytube_theme_preprocess_page(&$variables)
{
  $variables['logopath'] = '/' . drupal_get_path('theme', 'citytube_theme') . '/logo.svg';
}

/**
 * Implements hook_preprocess().
 */
function citytube_theme_preprocess(&$variables, $hook)
{
  try {
    $variables['is_node'] = \Drupal::routeMatch()->getParameter('node');
  } catch (Exception $e) {
    $variables['is_node'] = FALSE;
  }
}
